In [2]:
a1 = randi.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a1

array([1, 2, 3])

In [5]:
import numpy as np

In [6]:
a1 = randi.array([1,2,3])
a1

array([1, 2, 3])

In [8]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a1.shape

(3,)

In [11]:
a1.ndim

1

In [12]:
import pandas as pd

In [13]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
df = pd.DataFrame(a2)
df

     0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Arrays

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones = np.ones((2))
ones

array([1., 1.])

In [21]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[9, 1, 1, 9, 8],
       [8, 0, 2, 8, 7],
       [0, 6, 3, 6, 0]])

In [22]:
a2.shape

(2, 3)

In [30]:
np.random.seed(5)
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[3, 6, 6, 0, 9],
       [8, 4, 7, 0, 0],
       [7, 1, 5, 7, 0]])

# Viewing Array and Matrices

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a3[:2,:1,:3]

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])

In [35]:
a3.shape

(2, 3, 3)

## Manipulating & Comparing Arrays

### Arithmetic

In [1]:
a1

NameError: name 'a1' is not defined

In [2]:
a1

NameError: name 'a1' is not defined

In [3]:
import numpy as np

In [4]:
a1

NameError: name 'a1' is not defined

In [5]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
ones = np.ones(3)

In [7]:
ones

array([1., 1., 1.])

In [8]:
a2

NameError: name 'a2' is not defined

In [9]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [13]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [14]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [15]:
a3 ** 2

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[100, 121, 144],
        [169, 196, 225],
        [256, 289, 324]]])

In [16]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])

In [17]:
np.log(a2)

array([[0.        , 0.69314718, 1.19392247],
       [1.38629436, 1.60943791, 1.87180218]])

## Aggregation

In [18]:
massive_array = np.random.random(10000)

In [19]:
massive_array.size

10000

In [20]:
massive_array[:10]

array([0.19475682, 0.41079388, 0.17895998, 0.39751275, 0.01353489,
       0.21319274, 0.99507421, 0.11028771, 0.8674675 , 0.15214634])

In [21]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

282 μs ± 4.79 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
1.97 μs ± 8.99 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [1]:
np.std(a2)

NameError: name 'np' is not defined

In [2]:
import np as numpy

ModuleNotFoundError: No module named 'np'

In [3]:
import numpy as np

In [7]:
np.std(a2)

np.float64(1.8226964152656422)

In [5]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])

In [6]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [8]:
#demo of std & var
high_var_array = ([1, 100, 200, 300, 4000, 5000])
low_var_array = ([2, 4, 6, 8, 10])

## Reshaping & Transposing

In [9]:
a2.shape

(2, 3)

In [10]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [11]:
a2_reshape = a2.reshape(2,3,1)

In [12]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [13]:
a3.T.shape

(3, 3, 2)

## Dot Product

In [1]:
np.random.seed(0)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])

In [4]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
np.random.seed(0)

map1 = np.random.randint(10, size=(5,3))
map2 = np.random.randint(10, size=(5,3))

In [7]:
map1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [8]:
map2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [9]:
map1.shape , map2.shape

((5, 3), (5, 3))

In [10]:
np.dot(map1,map2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [11]:
np.dot(map1.T ,map2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [12]:
map3 = np.dot(map1.T ,map2)

In [13]:
map3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [14]:
map3.shape

(3, 3)

## Dot Product Example (nut butter sales)

In [21]:
import pandas as pd

In [25]:
np.random.seed(0)
#number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [26]:
#create weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amounts,
                              index = ["Mon","Tue","Wed","Thur","Fri"],
                              columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

      Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [31]:
#create prices array
prices = np.array([[10,8,12]])

In [32]:
#create butter_prices dataframes
butter_prices = pd.DataFrame(prices,
                            index = ["Price"],
                            columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [33]:
weekly_sales

      Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [34]:
weekly_sales["Total ($)"] = daily_sales

NameError: name 'daily_sales' is not defined

In [35]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

       Mon  Tue  Wed  Thur  Fri
Price  240  138  458   232  142

In [36]:
weekly_sales["Total ($)"] = daily_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)

In [37]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

      Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon              12             15              0        240
Tue               3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142

## Sorting Arrays

In [38]:
np.sort(a2)

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
random_array = np.random.randint(10, size = (3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [40]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [41]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])